# Generated by Django 6.1 on 2026-09-02 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Google Account, GitHub, Bank of America', max_length=255)),
                ('website_url', models.CharField(blank=True, default='', help_text='https://example.com', max_length=500)),
                ('username_or_email', models.CharField(help_text='Username, Email or Identifier', max_length=255)),
                ('encrypted_password', models.TextField(help_text='AES-256 Fernet Encrypted ciphertext')),
                ('category', models.CharField(choices=[('General', 'General'), ('Social', 'Social Media'), ('Banking', 'Banking & Finance'), ('Work', 'Work & Productivity'), ('Entertainment', 'Entertainment & Streaming'), ('Shopping', 'E-Commerce & Shopping'), ('Email', 'Email & Communication'), ('Development', 'Developer & Tech')], default='General', max_length=50)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional encrypted/plain notes')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Entry',
                'verbose_name_plural': 'Password Entries',
                'ordering': ['-is_favorite', '-updated_at'],
            },
        ),
    ]
